name: glitcher
description: Social App for Gamers

version: 1.0.16+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  firebase_storage: ^10.0.1
  firebase_dynamic_links: ^2.0.7
  firebase_messaging: ^10.0.4
  cloud_firestore: ^2.4.0
  shared_preferences: ^2.0.6
  file: ^6.1.2 #required for shared_preferences
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  google_sign_in: ^5.0.4
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.0.7
  flutter_svg: ^0.22.0
  image_picker: ^0.8.2
  path: ^1.8.0
  video_player: ^2.1.10
  chewie: ^1.2.2
  flutter_icons: ^1.1.0
  youtube_player_flutter: ^8.0.0
  toast: ^0.1.5
  modal_progress_hud: ^0.1.3
  soundpool: ^2.1.0
  dropdownfield: ^1.0.3
  autocomplete_textfield: ^1.7.3
  dropdown_formfield: ^0.1.1
  cached_network_image: ^3.1.0
  share: ^2.0.4
  curved_navigation_bar: ^1.0.1
  badges: ^2.0.1
  permission_handler: ^8.1.2
  random_string: ^2.3.1
  flutter_image_compress: ^1.0.0
  flutter_local_notifications: ^6.0.0
  intl: ^0.17.0
  flutter_typeahead: ^3.2.0
  photo_view: ^0.11.1
  extended_image: ^4.1.0
  image: ^3.0.2
  path_provider: ^2.0.2
  chewie_audio: ^1.2.0
  package_info: ^2.0.2
  connectivity: ^3.0.6
  readmore: ^2.1.0
  rate_my_app: ^1.1.0+1
  page_transition: ^2.0.2
  url_launcher: ^6.0.9
  loading_gifs: ^0.3.0
  mailer: ^5.0.1
  flutter_email_sender: ^5.0.2
  google_fonts: ^2.1.0
  flutter_facebook_login: ^3.0.0
  characters: ^1.1.0
  sqflite: ^2.0.0+3
  file_picker: ^3.0.3
  shimmer: ^2.0.0
  #video_compress: ^2.1.1
  provider: ^5.0.0
  animations: ^2.0.1
  record: ^3.0.0
  just_audio: ^0.7.1
  stack: ^0.2.1
  video_thumbnail: ^0.4.3
  firebase_remote_config: ^0.10.0+3
  webview_flutter: 2.0.4
  #in_app_update: ^2.0.0
  pull_to_refresh: 2.0.0
  flutter_bloc: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^9.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf